version: '3'
services:
    redis-server:
        image: 'redis'           # Builds from image
    node-app:
        restart: on-failure      # If this container crashes, apply this restart policy
        build: .                 # Builds from Dockerfile
        ports:
            - "8081:8081"        # '-' specifies array (can map multiple ports)
